pay:
    resource: UVd\PaymentBundle\Controller\PaymentController
    type:     rest
    prefix:   /payment

user:
    resource: UVd\UserBundle\Controller\UserController
    type:     rest
    prefix:   /user

fos_user_security_check:
    path: /security/login
    defaults: { _controller: FOSUserBundle:Security:check, _format: json }
    methods: [POST]
    requirements:
        _format:  json