parameters:
    vendor_security.authentication_handler: UVd\UserBundle\Handler\AuthenticationHandler

services:
    authentication_handler:
        class:  %vendor_security.authentication_handler%
        arguments:  [@fos_rest.view_handler]
        tags:
            - { name: 'monolog.logger', channel: 'security' }