parameters:
    uvd.subscription.subscription_manager.class: UVd\SubscriptionBundle\Manager\SubscriptionManager
    uvd.subscription.entity.subscription.class: UVd\SubscriptionBundle\Entity\Subscription
    uvd.subscription.stipe_listener_pre_persist.class: UVd\SubscriptionBundle\Listener\StripeListenerPrePersist

services:
    uvd.subscription.subscription_manager:
        class: %uvd.subscription.subscription_manager.class%
        parent: uvd.payment.base_manager
        arguments: [%uvd.subscription.entity.subscription.class%]

    uvd.subscription.stripe_pre_persist_listener:
        class: %uvd.subscription.stipe_listener_pre_persist.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }
        arguments:    [@service_container, @uvd.payment.stripe_proxy]